import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

// Color kMainColor = Color(0xFF39c526);
Color kMainColor = Color(0xFFF06135);
Color kMainPageBGColor = Color(0xfff8f8f8);
Color kDisabledColor = Color(0xff616161);
Color kTextColor = Color(0xfffff9e9);
Color kWhiteColor = Colors.white;
Color kLightTextColor = Color(0xff747474);
Color kCardBackgroundColor = Color(0xfff8f9fd);
Color kHomeIconColor = Color(0xf8e8eaf8);
Color kTransparentColor = Colors.transparent;
Color kMainTextColor = Color(0xff000000);
Color kBlackColor = Color(0xff000000);
Color kIconColor = Color(0xff000000);
Color kHintColor = Color(0xffa3a3a3);
Color kNavigationButtonColor = Color(0xffd09b1a);
Color kContainerTextColor = Color(0xff606060);
Color kButtonColor = Color(0xfffafafa);
Color kButtonBorderColor = Color(0xffe1e1e1);
Color kButtonTextColor = Color(0xffbababa);
Color kPopBackGround = Color(0xfffffafa);
Color kContainerShadowColor = Color(0xff87fddc82);
Color kRedColor = Color(0xffdc143c);
Color kMarqueeColor = Color(0xffffffff);
Color kPercentageBackC = Color(0xffFFA500);
// Color kDateCircleColor = Color(0xFF39c526);
Color kDateCircleColor = Color(0xFFF06135);
